version: '3'
services:
  app:
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
      args:
        - VARIANT=1.16
        - INSTALL_NODE=true
        - NODE_VERSION=lts/*
    volumes:
      - ../:/go/github.com/MasatoTokuse/actions-example
    working_dir: /go/github.com/MasatoTokuse/actions-example
    tty: true
    stdin_open: true
    command: /bin/bash